version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: m_mysql
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - my-datavolume:/var/lib/mysql
    environment:
      MYSQ_CONNECTION: mysql
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wallpaper_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
  redis:
    image: redis:latest
    container_name: m_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '63790:6379'
    expose:
      - '63790'
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m_app
    ports:
      - "8080:8080"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    restart: always

volumes:
  my-datavolume:



