version: "3"
services:
  master:
    container_name: redis-master
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - sentinel-master
  slave1:
    image: redis:latest
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - master
    networks:
      - sentinel-master
  slave2:
    image: redis:latest
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - master
    networks:
      - sentinel-master

volumes:
  my-datavolume:

networks:
  sentinel-master:
    external: true
