version: '3'
services:
  acgserver:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     - env=value
    image: acgserver/acg_server:latest
    environment:
      - NODE_ENV=production
      - EGG_SERVER_ENV=prod
      - EGG_REDIS_DB=0
      - EGG_REDIS_HOST=redis
      - EGG_REDIS_PORT=6379
      - EGG_REDIS_PASSWORD=12345678
      - EGG_MONGODB_URL=mongodb://127.0.0.1/acg_server
      - EGG_MINI_ASSETS=true
      - EGG_PASSPORT_GITHUB_CLIENT_ID=test
      - EGG_PASSPORT_GITHUB_CLIENT_SECRET=test
      # - EGG_SITE_STATIC_HOST=${EGG_SITE_STATIC_HOST}
      - EGG_ALINODE_APPID=appid
      - EGG_ALINODE_SECRET=secret
    depends_on:
      - redis
      - mongodb
    networks:
      - docker_acgserver
    ports:
      - 7001:7001

  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes --requirepass acg_server
    volumes:
      - egg-redis:/data
    networks:
      - docker_acgserver
    # ports:
    #   - 6379:6379

  mongodb:
    image: mongo:3.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=acg_server
    volumes:
      - egg-mongo:/data/db
      - ./init.d/mongo:/docker-entrypoint-initdb.d
    networks:
      - docker_acgserver
    # ports:
    #   - 27017:27017

volumes:
  egg-mongo:
  egg-redis:

networks:
  docker_acgserver:
    driver: bridge
