
Server:
  Runmode: debug                 # 开发模式, debug, release, test
  HttpPort: 3000
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:3000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png

Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx
  Password: xxx
  IsSSL: true
  From: xxx
  To:
    - xxx

JWT:
  Secret: yintokey
  Issuer: unsplash-service
  Expire: 7200

Database:
  DBType: mysql
  DBName: "wallpaper_db"
  Host: 127.0.0.1:3306
  #Host: docker.for.mac.localhost:3306
  #addr: docker.for.mac.localhost:3306
  Username: root
  Password: 12345678
  # config: "charset=utf8&parseTime=True&loc=Local"
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

Redis:
  Address: 127.0.0.1:6379 # Redis端口和地址
  Password: "" # Redis连接密码
  DB: "" # Redis库从0到10，不填即为0
  MaxRetry: 1
