// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: unsp.proto

package unsplashPackage

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//请求参数
type UnPictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *UnPictureRequest) Reset() {
	*x = UnPictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnPictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnPictureRequest) ProtoMessage() {}

func (x *UnPictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnPictureRequest.ProtoReflect.Descriptor instead.
func (*UnPictureRequest) Descriptor() ([]byte, []int) {
	return file_unsp_proto_rawDescGZIP(), []int{0}
}

func (x *UnPictureRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UnPictureRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// DTO
type UnPictureInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Piclist []*UnPictureInfo_Picture `protobuf:"bytes,1,rep,name=Piclist,proto3" json:"Piclist,omitempty"`
}

func (x *UnPictureInfo) Reset() {
	*x = UnPictureInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unsp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnPictureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnPictureInfo) ProtoMessage() {}

func (x *UnPictureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_unsp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnPictureInfo.ProtoReflect.Descriptor instead.
func (*UnPictureInfo) Descriptor() ([]byte, []int) {
	return file_unsp_proto_rawDescGZIP(), []int{1}
}

func (x *UnPictureInfo) GetPiclist() []*UnPictureInfo_Picture {
	if x != nil {
		return x.Piclist
	}
	return nil
}

type UnPictureInfo_Picture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PictureId     string  `protobuf:"bytes,1,opt,name=PictureId,proto3" json:"PictureId,omitempty"`
	ImageUrl      string  `protobuf:"bytes,2,opt,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	LargeImageUrl string  `protobuf:"bytes,3,opt,name=LargeImageUrl,proto3" json:"LargeImageUrl,omitempty"`
	Description   string  `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Author        string  `protobuf:"bytes,5,opt,name=Author,proto3" json:"Author,omitempty"`
	Name          string  `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	Width         float32 `protobuf:"fixed32,7,opt,name=Width,proto3" json:"Width,omitempty"`
	Height        float32 `protobuf:"fixed32,8,opt,name=Height,proto3" json:"Height,omitempty"`
	Likes         float32 `protobuf:"fixed32,9,opt,name=Likes,proto3" json:"Likes,omitempty"`
}

func (x *UnPictureInfo_Picture) Reset() {
	*x = UnPictureInfo_Picture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unsp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnPictureInfo_Picture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnPictureInfo_Picture) ProtoMessage() {}

func (x *UnPictureInfo_Picture) ProtoReflect() protoreflect.Message {
	mi := &file_unsp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnPictureInfo_Picture.ProtoReflect.Descriptor instead.
func (*UnPictureInfo_Picture) Descriptor() ([]byte, []int) {
	return file_unsp_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UnPictureInfo_Picture) GetPictureId() string {
	if x != nil {
		return x.PictureId
	}
	return ""
}

func (x *UnPictureInfo_Picture) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UnPictureInfo_Picture) GetLargeImageUrl() string {
	if x != nil {
		return x.LargeImageUrl
	}
	return ""
}

func (x *UnPictureInfo_Picture) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UnPictureInfo_Picture) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UnPictureInfo_Picture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnPictureInfo_Picture) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UnPictureInfo_Picture) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UnPictureInfo_Picture) GetLikes() float32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

var File_unsp_proto protoreflect.FileDescriptor

var file_unsp_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x6e, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x75, 0x6e,
	0x73, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x42, 0x0a,
	0x10, 0x55, 0x6e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0xcf, 0x02, 0x0a, 0x0d, 0x55, 0x6e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x40, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x75, 0x6e, 0x73, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x6e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x07, 0x50, 0x69,
	0x63, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xfb, 0x01, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x4c,
	0x61, 0x72, 0x67, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x4c, 0x69,
	0x6b, 0x65, 0x73, 0x32, 0x69, 0x0a, 0x10, 0x55, 0x6e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x6e,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x2e, 0x75, 0x6e,
	0x73, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x6e,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x75, 0x6e, 0x73, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2e, 0x55, 0x6e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unsp_proto_rawDescOnce sync.Once
	file_unsp_proto_rawDescData = file_unsp_proto_rawDesc
)

func file_unsp_proto_rawDescGZIP() []byte {
	file_unsp_proto_rawDescOnce.Do(func() {
		file_unsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_unsp_proto_rawDescData)
	})
	return file_unsp_proto_rawDescData
}

var file_unsp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_unsp_proto_goTypes = []interface{}{
	(*UnPictureRequest)(nil),      // 0: unsplashPackage.UnPictureRequest
	(*UnPictureInfo)(nil),         // 1: unsplashPackage.UnPictureInfo
	(*UnPictureInfo_Picture)(nil), // 2: unsplashPackage.UnPictureInfo.Picture
}
var file_unsp_proto_depIdxs = []int32{
	2, // 0: unsplashPackage.UnPictureInfo.Piclist:type_name -> unsplashPackage.UnPictureInfo.Picture
	0, // 1: unsplashPackage.UnPictureService.GetUnPictureInfo:input_type -> unsplashPackage.UnPictureRequest
	1, // 2: unsplashPackage.UnPictureService.GetUnPictureInfo:output_type -> unsplashPackage.UnPictureInfo
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_unsp_proto_init() }
func file_unsp_proto_init() {
	if File_unsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnPictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unsp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnPictureInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unsp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnPictureInfo_Picture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unsp_proto_goTypes,
		DependencyIndexes: file_unsp_proto_depIdxs,
		MessageInfos:      file_unsp_proto_msgTypes,
	}.Build()
	File_unsp_proto = out.File
	file_unsp_proto_rawDesc = nil
	file_unsp_proto_goTypes = nil
	file_unsp_proto_depIdxs = nil
}
